### ISSUE TITLE
Ability to deploy to .workers.dev?

### ISSUE THREAD

**Issue by rschristian** [lukeed/cfw#7]
First off, apologies if this is a misunderstanding, first time playing with workers so I still have a lot of doc reading to do.

It seems that `cfw` can only deploy to custom domains, hence the requirement on having a `zoneid`. Is this intentional, or maybe a limitation on CF's side? As I don't have any domains set up with CF at the moment, there's no way to get a `zoneid` for quick demo of `worktop` + `cfw`. Had to switch over to `wrangler` for that.

Certainly not a huge deal as anything past a demo I'd want to toss up on a real domain anyhow.

**Comment by lukeed** [comment]
Hey,

Ya I plan on adding this. In the meantime you can put in a junk zoneid and leave your `routes` empty. This allows the script to be uploaded.

Then after your first upload, you go into your dashboard and manually turn on the "deploy to workers subdomain" toggle. This persists across deployments, so all future deploys will keep going to your subdomain.

**Comment by rschristian** [comment]
Oh cool! Didn't even think to try a junk id, certainly wouldn't expect that to persist. Good to know!

**Comment by lukeed** [comment]
The `zoneid` is just needed to define the routes :) I do throw an error if the value is empty, but if it's invalid-but-never-used then it's not a problem, haha

I'll add something nicer of course, but I havent decided yet how to deal with multiple environments, and I think that's how/where a `subdomain: boolean` value should come in.

**Comment by simplenotezy** [comment]
@lukeed How would we go about testing locally on a workers.dev domain?

**Comment by lukeed** [comment]
See tagged commit and PR; use ‘subdomain: true’ in config file

**Comment by simplenotezy** [comment]
Very cool, thanks - missed that

**Comment by simplenotezy** [comment]
@lukeed is there a way to run it in "watch" mode? So it hot-reloads on changes?

**Comment by lukeed** [comment]
Redeploy on every file save? You’d have to use an external file watcher; eg:

watchlist src — cfw deploy
